resources:
- cos-s3-csi-controller.yaml 
- cos-s3-csi-driver.yaml
- cos-s3-csi-sc.yaml
- cos-s3-csi-rclone-sc.yaml
- cos-s3-csi-s3fs-sc.yaml
- cos-s3-csidriver.yaml
images:
- name: csi-attacher-image
  newName: k8s.gcr.io/sig-storage/csi-attacher
  newTag: v4.2.0
- name: csi-provisioner-image
  newName: k8s.gcr.io/sig-storage/csi-provisioner
  newTag: v3.4.1
- name: cos-driver-image
  newName: quay.io/containerstorage/ibm-object-csi-driver
  newTag: v2
- name: driver-registrar-image
  newName: k8s.gcr.io/sig-storage/csi-node-driver-registrar
  newTag: v2.6.3
- newName: registry.k8s.io/sig-storage/livenessprobe
  newTag: v2.9.0
  name: liveness-probe-image
