apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cos-s3-csi-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: cos-s3-csi-sc
