---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-provisioner
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner-rolebind
subjects:
  - kind: ServiceAccount
    name: csi-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: csi-provisioner-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Service
apiVersion: v1
metadata:
  name: cos-csi-s3-provisioner
  labels:
    app: cos-csi-s3-provisioner
spec:
  selector:
    app: cos-csi-s3-provisioner
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: cos-csi-s3-provisioner
spec:
  serviceName: "cos-csi-s3-provisioner"
  replicas: 1
  selector:
    matchLabels:
      app: cos-csi-s3-provisioner
  template:
    metadata:
      labels:
        app: cos-csi-s3-provisioner
    spec:
      serviceAccountName: csi-provisioner
      containers:
        - name: csi-provisioner
          # https://github.com/kubernetes-csi/external-provisioner/releases
          # https://github.com/kubernetes-csi/external-provisioner/releases/tag/v1.0.1
          # docker pull quay.io/k8scsi/csi-provisioner:v1.0.1
          # image: gcr.io/gke-release/csi-provisioner:v1.0.1-gke.0
          image: nkkashyap/csi-provisioner:v1.1.1
          args:
            - "--provisioner=cos-csi-s3-driver"
            - "--csi-address=$(ADDRESS)"
            - "--connection-timeout=15s"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: csi-s3-provisioner
          image: ibm/satellite-object-storage-plugin
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(NODE_ID)"
            - "--logtostderr=true"
            - "--v=4"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: "Never"
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-s3-driver
            type: DirectoryOrCreate
          name: socket-dir
