---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cos-s3-csi-attacher
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cos-s3-csi-attacher-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cos-s3-csi-attacher-rolebind
subjects:
  - kind: ServiceAccount
    name: cos-s3-csi-attacher
    namespace: default
roleRef:
  kind: ClusterRole
  name: cos-s3-csi-attacher-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Service
apiVersion: v1
metadata:
  name: cos-s3-csi-attacher
  labels:
    app: cos-s3-csi-attacher
spec:
  selector:
    app: cos-s3-csi-attacher
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: cos-s3-csi-attacher
spec:
  serviceName: "cos-s3-csi-attacher"
  replicas: 1
  selector:
    matchLabels:
      app: cos-s3-csi-attacher
  template:
    metadata:
      labels:
        app: cos-s3-csi-attacher
    spec:
      serviceAccountName: cos-s3-csi-attacher
      containers:
        - name: csi-attacher
          image: csi-attacher-image
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
      volumes:
        - hostPath:
            path: /var/data/kubelet/csi-plugins/cos.s3.csi.ibm.io
            type: DirectoryOrCreate
          name: socket-dir
