---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibm-object-storage-standard-rclone-retain
  labels:
    ibm.cos.storageclass/tier: standard
provisioner: cos.s3.csi.ibm.io
mountOptions:
    - "acl=private"
    - "bucket_acl=private"
    - "upload_cutoff=256Mi"
    - "chunk_size=64Mi"
    - "max_upload_parts=64"
    - "upload_concurrency=20"
    - "copy_cutoff=1Gi"
    - "memory_pool_flush_time=30s"
    - "disable_checksum=true"
parameters:
  mounter: "rclone"
  client: "awss3"
  cosEndpoint: "https://s3.direct.us-west.cloud-object-storage.appdomain.cloud"
  locationConstraint: "us-west-standard"
  csi.storage.k8s.io/provisioner-secret-name: ${pvc.name}
  csi.storage.k8s.io/provisioner-secret-namespace: ${pvc.namespace}
  csi.storage.k8s.io/node-publish-secret-name: ${pvc.name}
  csi.storage.k8s.io/node-publish-secret-namespace: ${pvc.namespace}
reclaimPolicy: Retain
