apiVersion: v1
kind: Secret
type: cos-s3-csi-driver
metadata:
  name: cos-rclone-secret
data:
  # Bucket name: echo -n "nkcode-devtest01" | base64
  bucketName: bmtjb2RlLWRldnRlc3QwMQ==
  # apiKey:      # base64 encoded IAM API Key
  # serviceId:   # base64 encoded IAM Service Instance ID
  # iamEndpoint: # base64 encoded IAM Endpoint
  # HMAC Access Key and Secret Key
  # echo -n "<access kye>" | base64
  # echo -n "<secret kye>" | base64
  accessKey: bXktYWNjZXNzLWtleQ==
  secretKey: bXktc2VjcmV0LWtleQ==
  # echo -n <kpRootKeyCRN> | base64
  # kpRootKeyCRN: # base64 encoded Key Protect Root key CRN
stringData:
  # uid: "3000" # Provide uid to run as non root user. This must match runAsUser in SecurityContext of pod spec.
  mountOptions: |
