apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cos-rclone-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: ibm-object-storage-smart-rclone
