kind: Pod
apiVersion: v1
metadata:
  name: cos-csi-app-rclone
spec:
  containers:
    - name: app-frontend
      image: gcr.io/google-samples/node-hello:1.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: "/data/rclone"
        name: cos-csi-volume
  volumes:
    - name: cos-csi-volume
      persistentVolumeClaim:
        claimName: cos-rclone-pvc
