apiVersion: v1
kind: Secret
type: cos-s3-csi-driver
metadata:
  name: cos-s3fs-secret
  namespace: default
data:
  # Bucket name: echo -n "nkcode-devtest01" | base64
  bucketName: YmhhLU1hcjI1MDE=
  # apiKey:      # base64 encoded IAM API Key
  # serviceId:   # base64 encoded IAM Service Instance ID
  # HMAC Access Key and Secret Key
  # echo -n "<access kye>" | base64
  # echo -n "<secret kye>" | base64
  accessKey: NzFmZTM1NTI4MmM4NDBkMWI5YTQ1MzcyNDRhOWI5OWM=
  secretKey: ZGVlYTZhYmI5OGY4MjIwODlhZmVhYTUyNjA0YTM3MTNmYTQzODI4ZGIzNGM0YTU4
  # echo -n <kpRootKeyCRN> | base64
  # kpRootKeyCRN: # base64 encoded Key Protect Root key CRN
stringData:
  # uid: "3000" # Provide uid to run as non root user. This must match runAsUser in SecurityContext of pod spec.
  mountOptions: |
