apiVersion: v1
kind: Secret
type: cos-s3-csi-driver
metadata:
  name: cos-s3fs-secret
  namespace: default
data:
  # Bucket name: echo -n "nkcode-devtest01" | base64
  bucketName: cHNhLXZlcnNpb25kcml2ZS10ZXN0
  # apiKey:      # base64 encoded IAM API Key
  # serviceId:   # base64 encoded IAM Service Instance ID
  # HMAC Access Key and Secret Key
  # echo -n "<access kye>" | base64
  # echo -n "<secret kye>" | base64
  accessKey: YjM2NTNjNmVmMzY2NDE0ZGFiOTgzNTU4MTgxYTY1MzQ=
  secretKey: ZDJiOTMzYWMzMTg4Mzc2YWRlMzE5OGZlMjZhZTIxYTI1ODJmNWMwYzg5MGJlNGVm
  # echo -n <kpRootKeyCRN> | base64
  # kpRootKeyCRN: # base64 encoded Key Protect Root key CRN
stringData:
  # uid: "3000" # Provide uid to run as non root user. This must match runAsUser in SecurityContext of pod spec.
  mountOptions: |


